### ISSUE TITLE
Lookup by case name

### ISSUE THREAD

**Issue by anseljh** [anseljh/casebot#3]
e.g. `@casebot lookup Roe v. Wade`

@mlissner says: "does a search on the API case name field, returns first result"

**Comment by mlissner** [comment]
Example query using the search endpoint and looking in the case name field: 

https://www.courtlistener.com/api/rest/v3/search/?q=casename:(roe%20v.%20wade)

That returns three results, but the first is (probably) the Roe you want. If you put this in production, you'd also want to do some [authentication](https://www.courtlistener.com/api/rest-info/#authentication) because you'll get throttled otherwise (though maybe not if you have low enough traffic).
